### PR TITLE
Addresses issue #48 ammeter fails if not using fixtures

### PR DESCRIPTION
**Pull request by bigtunacan**
I was getting a failure `uninitialized constant RSpec::Rails::FixtureSupport`.  There appears to be an an open issue for this already #48 that was being worked on, but a pull request never was created.

I built the gem, cloned, updated the dependency within rspec-rails and ran test suite there.  Everything is a clean build.

### CODE REVIEW

**Comment by bigtunacan** [comment]
@alexrothenberg Little confused on why the test suite is failing here.  The `When I run "rake spec"` steps expect different output for the separate features, but every time it runs it just comes back with 37 example, 0 failures.

**Comment by alexrothenberg** [comment]
Thank you for working on this fix!

I think I see 2 failures I pushed your code plus a bit more from me up at https://github.com/alexrothenberg/ammeter/commits/bigtunacan-master.

1. The 37 vs 4 weirdness seems to be due to spring running from `tmp/example_app` after that dir is deleted and recreated.  Its just a testing artifact and I fixed that by stopping spring in 24a9966
2. There's another problem that I think is real. When you are using ammeter in a gem that uses `railties` there's some sort of cyclic requiring with the gem + ammeter + rspec-rails all requiring parts of rails (in a way I don't quite understand).  

You can see this in action if you checkout https://github.com/alexrothenberg/ammeter/commits/bigtunacan-master and run

```
cd tmp/aruba
bundle
rake spec
```

I'll try to keep looking when I can but am not sure how hard this will be to figure out.

Again thanks for this contribution and once we can figure out the gem use case - I remember adding it from someone's real life scenario so we can't get rid of it - I'll happily merge it in and release a new version!

**Comment by d4rky-pl** [comment]
```
joker:aruba d4rky$ rake spec
(in /Users/d4rky/htdocs/ammeter)
/Users/d4rky/.rvm/rubies/ruby-2.2.2/bin/ruby -I/Users/d4rky/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib:/Users/d4rky/.rvm/gems/ruby-2.2.2/gems/rspec-support-3.3.0/lib /Users/d4rky/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb --color
.....................................

Finished in 0.27837 seconds (files took 1.1 seconds to load)
37 examples, 0 failures
```

Can't reproduce the `rake spec` error on my machine, might be something environment or version related.

**Comment by derekprior** [comment]
@alexrothenberg Do you think it'd be possible to get a release with this fix?

**Comment by alexrothenberg** [comment]
@derekprior sorry for the delay.  Just released 1.1.3 to rubygems.

**Pull request merged**
